print("hallo nama ku bill")
print("aku suka kamu tapi kamu ga suka aku")
print("aku menerima kamu apa adanya")
print("aku hanya ingin kegelapan")
print("hanya bisa melihat mu tapi tidak bisa memiliki mu")
print("heart full of darknes")
print("life is pain full to be better")
print("ya sudah apa lagi yang harus ku perjuangkan")
print("aku tau kok kamu lebih suka cowo lain")
print("sekian kata kata ku terimakasih")